spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/perfectjob
    username: perfectjob
    password: perfectjob
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    com.perfectjob: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
