spring:
  datasource:
    url: jdbc:tc:postgresql:17:///perfectjob_test
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    enabled: false

logging:
  level:
    com.perfectjob: DEBUG
